# Generated by Django 6.0.3 on 2026-04-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_ip_address_device_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinglog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.feedingschedule'),
        ),
    ]
