# Generated by Django 6.0.3 on 2026-05-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_feedinglog_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('food_level', models.IntegerField(default=0)),
                ('water_level', models.IntegerField(default=0)),
                ('feed_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='online', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
